# Generated by Django 5.0 on 2023-12-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='پسندیدن'),
        ),
    ]
