# Generated by Django 5.0 on 2023-12-20 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_account', '0001_initial'),
        ('app_item', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان')),
                ('in_process', models.BooleanField(default=False, verbose_name='در حال انجام')),
                ('is_complete', models.BooleanField(default=False, verbose_name='تکمیل شده')),
                ('staff', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_account.staff', verbose_name='کارمند')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='OrderStaff',
            fields=[
            ],
            options={
                'verbose_name': 'سفارش من',
                'verbose_name_plural': 'سفارشات من',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_order.order',),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='تعداد')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_item.item', verbose_name='آیتم')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_order.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'آیتم سفارش شده',
                'verbose_name_plural': 'آیتم های سفارش شده',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(through='app_order.OrderItem', to='app_item.item', verbose_name='آیتم ها'),
        ),
    ]
