# Generated by Django 5.0 on 2023-12-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivemessage',
            name='read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
    ]
